# -*- coding: utf-8 -*-
"""Phân Tích & Dự Báo Kinh Doanh Tết 2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YlPSbpdjCy2hZ0NWWLTWTzVQgPGtxee_
"""

pip install faker pandas numpy

import pandas as pd
from faker import Faker
import random
from datetime import datetime, timedelta

fake = Faker(['vi_VN'])
Faker.seed(42)

# --- 1. Dim_Customers (Tăng lên 500 khách hàng cho đa dạng) ---
num_customers = 500
customers = []
for _ in range(num_customers):
    customers.append({
        'CustomerID': fake.unique.random_int(min=10000, max=99999),
        'CustomerName': fake.name(),
        'City': random.choice(['Hà Nội', 'TP. Hồ Chí Minh', 'Đà Nẵng', 'Cần Thơ', 'Hải Phòng']),
        'Segment': random.choice(['VIP', 'Loyal', 'New', 'Potential'])
    })
dim_customers = pd.DataFrame(customers)

# --- 2. Dim_Products ---
products_data = [
    ('T01', 'Giỏ quà Xuân Như Ý', 'Giỏ quà', 550000),
    ('T02', 'Bánh chưng nếp nương', 'Đồ cúng', 120000),
    ('B01', 'Thùng Bia 24 lon', 'Nước giải khát', 380000),
    ('K01', 'Mứt dừa Bến Tre', 'Bánh kẹo', 85000),
    ('G01', 'Bộ bát đĩa gốm sứ', 'Gia dụng', 450000)
]
dim_products = pd.DataFrame(products_data, columns=['SKU', 'ProductName', 'Category', 'Price'])

# --- 3. Fact_Sales (Tạo 1000 dòng giao dịch) ---
sales = []
total_rows = 1000
start_date = datetime(2025, 12, 1)
end_date = datetime(2026, 2, 15)

# Định nghĩa các mốc thời gian Tết theo hình số 5 bạn gửi
pre_tet_start = datetime(2026, 1, 15)
pre_tet_end = datetime(2026, 1, 28)
tet_days = [datetime(2026, 1, 29), datetime(2026, 1, 30), datetime(2026, 1, 31)]

for _ in range(total_rows):
    # Chọn ngày ngẫu nhiên nhưng ưu tiên dồn vào giai đoạn Pre-Tet để mô phỏng mùa vụ
    if random.random() < 0.6: # 60% dữ liệu rơi vào Pre-Tet
        order_date = fake.date_between_dates(date_start=pre_tet_start, date_end=pre_tet_end)
    else:
        order_date = fake.date_between_dates(date_start=start_date, date_end=end_date)

    # Ép kiểu về datetime để so sánh
    order_date = datetime.combine(order_date, datetime.min.time())

    prod = dim_products.sample(1).iloc[0]

    # Logic số lượng: Pre-Tet mua nhiều hơn (giỏ quà, bia)
    if pre_tet_start <= order_date <= pre_tet_end:
        qty = random.randint(3, 15) if prod['Category'] in ['Giỏ quà', 'Nước giải khát'] else random.randint(1, 5)
    elif order_date in tet_days:
        qty = random.randint(1, 2) # Ngày Tết bán rất ít
    else:
        qty = random.randint(1, 3)

    sales.append({
        'OrderID': fake.unique.bothify(text='INV-######'),
        'OrderDate': order_date,
        'CustomerID': random.choice(dim_customers['CustomerID'].values),
        'SKU': prod['SKU'],
        'Quantity': qty,
        'TotalAmount': qty * prod['Price'],
        'Channel': random.choice(['Shopee', 'Lazada', 'Facebook', 'Offline Store']),
        'Region': random.choice(['Miền Bắc', 'Miền Trung', 'Miền Nam'])
    })

fact_sales = pd.DataFrame(sales).sort_values('OrderDate')
print(f"Đã tạo xong {len(fact_sales)} dòng dữ liệu giao dịch!")

import sqlite3

# 1. Kết nối file database
conn = sqlite3.connect('tet_sales_warehouse.db')

# 2. Lưu các DataFrame  vào các bảng SQL
fact_sales.to_sql('fact_sales', conn, if_exists='replace', index=False)
dim_customers.to_sql('dim_customers', conn, if_exists='replace', index=False)
dim_products.to_sql('dim_products', conn, if_exists='replace', index=False)

print("Đã lưu 1.000 dòng vào Data Warehouse SQLite!")

# Truy vấn
query_metrics = """
SELECT
    COUNT(DISTINCT OrderID) as Total_Orders,
    SUM(TotalAmount) as GMV,
    SUM(TotalAmount) / COUNT(DISTINCT OrderID) as AOV
FROM fact_sales;
"""

metrics_df = pd.read_sql(query_metrics, conn)
print(metrics_df)

query_sku_analysis = """
SELECT
    SKU,
    SUM(TotalAmount) as SKU_GMV,
    (SUM(TotalAmount) * 100.0 / (SELECT SUM(TotalAmount) FROM fact_sales)) as Contribution_Percentage
FROM fact_sales
GROUP BY SKU
ORDER BY SKU_GMV DESC;
"""

sku_analysis = pd.read_sql(query_sku_analysis, conn)
print(sku_analysis)

import gradio as gr
import pandas as pd
import sqlite3
import os
from datetime import timedelta

# Đảm bảo đường dẫn file database chính xác khi chạy trên server
DB_PATH = "tet_sales_warehouse.db"

def get_comprehensive_analytics(region_filter):
    # Kiểm tra nếu file DB tồn tại
    if not os.path.exists(DB_PATH):
        return None, None, None, None, None

    conn = sqlite3.connect(DB_PATH)
    where_clause = "" if region_filter == "Tất cả" else f"WHERE f.Region = '{region_filter}'"

    # 1. Hiệu suất Sản phẩm & Danh mục
    df_sku = pd.read_sql(f"""
        SELECT p.ProductName, p.Category, SUM(f.TotalAmount) as GMV
        FROM fact_sales f
        JOIN dim_products p ON f.SKU = p.SKU
        {where_clause}
        GROUP BY p.ProductName, p.Category ORDER BY GMV DESC
    """, conn)

    # 2. Xu hướng & Dự báo
    df_trend = pd.read_sql(f"""
        SELECT OrderDate, SUM(TotalAmount) as Daily_Sales
        FROM fact_sales f {where_clause}
        GROUP BY OrderDate ORDER BY OrderDate
    """, conn)
    df_trend['OrderDate'] = pd.to_datetime(df_trend['OrderDate'])

    # Logic Dự báo 7 ngày
    avg_recent = df_trend['Daily_Sales'].tail(7).mean()
    last_date = df_trend['OrderDate'].max()
    forecast_list = []
    for i in range(1, 8):
        forecast_list.append({
            'OrderDate': last_date + timedelta(days=i),
            'Daily_Sales': avg_recent * (1.05 ** i),
            'Type': 'Dự báo'
        })
    df_forecast = pd.DataFrame(forecast_list)
    df_actual = df_trend.copy(); df_actual['Type'] = 'Thực tế'
    df_combined_trend = pd.concat([df_actual, df_forecast])

    # 3. So sánh Khu vực
    df_region = pd.read_sql("SELECT Region, SUM(TotalAmount) as GMV FROM fact_sales GROUP BY Region", conn)

    # 4. Tồn kho DOS
    df_inv = pd.read_sql(f"""
        SELECT p.ProductName, SUM(f.Quantity) as Sold, (2000 - SUM(f.Quantity)) as On_Hand
        FROM fact_sales f JOIN dim_products p ON f.SKU = p.SKU
        GROUP BY p.ProductName
    """, conn)
    df_inv['DOS'] = df_inv['On_Hand'] / (df_inv['Sold'].replace(0, 1) / 45)

    conn.close()
    return df_combined_trend, df_region, df_sku, df_sku, df_inv

# Giao diện Blocks
with gr.Blocks(title="🧧 Hệ Thống Quản Trị Tết") as demo:
    gr.Markdown("# 🧧 Dashboard Phân Tích & Dự Báo Kinh Doanh Tết 2026")
    region_dropdown = gr.Dropdown(choices=["Tất cả", "Miền Bắc", "Miền Trung", "Miền Nam"], value="Tất cả", label="📍 Lọc theo Khu vực")

    with gr.Tab("📈 Xu Hướng & Dự Báo"):
        forecast_plot = gr.LinePlot(x="OrderDate", y="Daily_Sales", color="Type", title="Báo cáo Xu hướng & Dự báo", width=900)

    with gr.Tab("📊 Hiệu Suất Sản Phẩm"):
        with gr.Row():
            sku_plot = gr.BarPlot(x="ProductName", y="GMV", color="Category", title="GMV theo Sản phẩm", vertical=False)
            sku_table = gr.DataFrame(label="Chi tiết Danh mục")

    with gr.Row():
        region_plot = gr.BarPlot(x="Region", y="GMV", title="GMV theo Miền", color="Region")
        dos_plot = gr.BarPlot(x="ProductName", y="DOS", title="Số ngày đủ bán dự kiến", color="ProductName")

    region_dropdown.change(get_comprehensive_analytics, inputs=[region_dropdown], outputs=[forecast_plot, region_plot, sku_plot, sku_table, dos_plot])
    demo.load(get_comprehensive_analytics, inputs=[region_dropdown], outputs=[forecast_plot, region_plot, sku_plot, sku_table, dos_plot])

# Không dùng share=True khi deploy lên Hugging Face
if __name__ == "__main__":
    demo.launch()